services:
  keycloak:
    #image: ghcr.io/opentdf/keycloak:21.1.2-1.4.2
    image: quay.io/keycloak/keycloak:latest
    restart: always
    command: ["start-dev"]
    environment:
      KC_HTTP_RELATIVE_PATH: /auth
      KC_DB_VENDOR: postgres
      KC_DB_URL_HOST: keycloakdb
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: changeme
      KC_HOSTNAME_PORT: "8888"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
      KC_HTTP_PORT: "8888"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: changeme
      KC_FEATURES: "preview,token-exchange"
    ports:
      - "8888:8888"
  keycloakdb:
    image: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: postgres
      POSTGRES_DB: keycloak
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
  opentdfdb:
    image: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: opentdf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
  opentdfdb-loader:
    depends_on:
      opentdfdb:
        condition: service_healthy
    build:
      context: ./tests
      dockerfile_inline: |
        FROM golang
        RUN go install github.com/pressly/goose/v3/cmd/goose@v3.16.0
        RUN apt-get update && apt-get install -y postgresql-client && rm -rf /var/lib/apt/lists/* postgresql
    command: ["/tests/initdb.d/import-dump.sh"]
    environment:
      SEED: ${SEED:-default}
      PGUSER: postgres
      PGPASSWORD: changeme
      PGDATABASE: opentdf
      PGHOST: opentdfdb
      PGSCHEMA: public
      GOOSE_DBSTRING: postgres://postgres:changeme@opentdfdb:5432/opentdf
      GOOSE_DRIVER: postgres
      GOOSE_MIGRATION_DIR: /migrations
    volumes:
      - ./migrations:/migrations
      - ./tests/initdb.d:/initdb.d
      - ./tests:/tests
